# server setting
server:
  port: 8080


# logging
logging:
  level:
    com.innim.okkycopy: trace
    org.springframework.security: trace

# spring
spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: resources/**